#pragma once

#include <array>
#include <cmath>

// Generated by scripts/export_value_model_header.py. Do not edit coefficients
// by hand.
namespace gen217_production_value_model {

static const int INPUT_SIZE = 18;
static const int PHASE_INDEX = 5;
static const int PHASE_DEGREE = 3;
static const int FEATURE_COUNT = 17;
static const double PHASE_DIVISOR = 92;
static const int FEATURE_INDICES[FEATURE_COUNT] = {
    0,
    1,
    2,
    3,
    4,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17
};
static const double FEATURE_DIVISORS[FEATURE_COUNT] = {
    92,
    92,
    92,
    92,
    32,
    92,
    92,
    92,
    128,
    32,
    32,
    32,
    8,
    4,
    128,
    16,
    48
};
static const double COEFFICIENTS[FEATURE_COUNT + 1][PHASE_DEGREE + 1] = {
    {-0.57575300399814877, 7.0664728103159966, -20.186231287420547, 17.074635952425041},
    {39.870665307280426, -222.76474331215562, 410.46390377038563, -226.92740990810375},
    {8.0189477832653999, -41.328785718223337, 70.427049194343738, -40.623825727618701},
    {-10.303853926210289, -15.342975853140281, 226.4791901183996, -280.50065986958509},
    {18.409812367111492, -132.10959099842185, 328.83359522087579, -246.61124480234531},
    {8.5395552387767424, -68.094912967008085, 183.7026698676755, -145.77249309898417},
    {0.97330780711246501, -4.0261901369651873, 6.9174407984044022, -12.20622343572551},
    {-1.2067842152338406, -54.635675585014781, 319.83014170307024, -452.10777596724472},
    {0.78175233870763772, -7.3726922943837145, 19.058067423597262, -7.3248179399437081},
    {-0.89402401984170876, 14.866611017370849, -67.083321088414166, 46.642885607550234},
    {-0.69275745665225741, 1.8197823449945247, -1.2921217368306488, 0.63463123288872669},
    {-8.0157795167279531, 67.303482162427329, -151.42200182053386, 104.97824668931777},
    {-5.0438079238667202, 30.803397109890394, -63.93587503051716, 42.005595523433399},
    {0.58962259571522257, 1.674386409916677, -18.132378203333907, 23.111379614526271},
    {-0.11960218728738155, 0.41159845784424842, 0.43379200434186527, -0.096235691845954707},
    {-2.585913407365481, 37.793161759416584, -63.028977205934176, 40.704492280440874},
    {-0.74958451013267802, 6.3339946000567338, -21.198976078507783, 23.59636178176693},
    {-0.44766165400714336, 2.0537162363553945, -8.5755182429434473, 10.839979888730859}
};

inline double polynomial(int group, double phase) {
    double value = COEFFICIENTS[group][PHASE_DEGREE];
    for (int degree = PHASE_DEGREE - 1; degree >= 0; --degree) {
        value = value * phase + COEFFICIENTS[group][degree];
    }
    return value;
}

inline double evaluate(const std::array<double, INPUT_SIZE>& raw) {
    double phase = raw[PHASE_INDEX] / PHASE_DIVISOR;
    if (phase < 0.0) phase = 0.0;
    if (phase > 1.0) phase = 1.0;
    double logit = polynomial(0, phase);
    for (int feature = 0; feature < FEATURE_COUNT; ++feature) {
        double normalized = raw[FEATURE_INDICES[feature]]
            / FEATURE_DIVISORS[feature];
        logit += normalized * polynomial(feature + 1, phase);
    }
    return std::tanh(0.5 * logit);
}

}  // namespace gen217_production_value_model
