#pragma once

#include <array>
#include <cmath>

// Generated by scripts/export_value_model_header.py. Do not edit coefficients
// by hand.
namespace gen217_value_model {

static const int INPUT_SIZE = 31;
static const int PHASE_INDEX = 5;
static const int PHASE_DEGREE = 3;
static const int FEATURE_COUNT = 17;
static const double PHASE_DIVISOR = 92;
static const int FEATURE_INDICES[FEATURE_COUNT] = {
    0,
    1,
    2,
    3,
    4,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17
};
static const double FEATURE_DIVISORS[FEATURE_COUNT] = {
    92,
    92,
    92,
    92,
    32,
    92,
    92,
    92,
    128,
    32,
    32,
    32,
    8,
    4,
    128,
    16,
    48
};
static const double COEFFICIENTS[FEATURE_COUNT + 1][PHASE_DEGREE + 1] = {
    {-0.49802617876907146, 7.3625653433724336, -22.065949748422483, 20.212541191669128},
    {40.269613694371451, -220.28790500336646, 399.37655295719031, -215.65359350459991},
    {7.4761304815790277, -37.697471169379511, 62.47260134720937, -34.589460441175724},
    {-11.144577393057153, -17.400538148444532, 253.77516153240938, -305.44398227547993},
    {18.479477887763991, -130.82009879824614, 326.77631817879592, -247.18343620115823},
    {8.3123614791154079, -71.214182632886377, 198.91847016447733, -162.76506510198342},
    {0.71642199785941385, -2.0482718389950203, 4.9405455798870204, -9.4026903928140619},
    {-1.5143384041574826, -54.617975970588844, 324.92471984612229, -464.07679452373554},
    {0.37117716382382637, -4.3798170656998661, 12.748983250725658, -7.6354347308285586},
    {-0.11993704599045928, 11.906081748799132, -69.632362420111704, 49.348610755332338},
    {-0.24259323145246225, 1.8759852952789478, -5.4264681905138961, 5.3693042091763461},
    {-7.777793744940678, 62.985937971848998, -135.78130498265145, 90.86889600611066},
    {-4.9582140931596941, 30.495954468167447, -62.707565685448493, 40.792988732628224},
    {0.29650883524232496, 2.9295425476618071, -18.124363598937563, 21.59027469929325},
    {-0.15297835073161445, 1.1565173257510923, -2.7178509066061811, 3.2865545051127061},
    {-3.3308191224777199, 40.480654598641671, -57.401498665939755, 33.833932371720813},
    {-0.72368040931862487, 6.4563264234962627, -22.670319419298419, 25.734602053283375},
    {-0.55003210868490793, 1.4488414879496663, -6.4307581085925856, 9.4093043823209719}
};

inline double polynomial(int group, double phase) {
    double value = COEFFICIENTS[group][PHASE_DEGREE];
    for (int degree = PHASE_DEGREE - 1; degree >= 0; --degree) {
        value = value * phase + COEFFICIENTS[group][degree];
    }
    return value;
}

inline double evaluate(const std::array<double, INPUT_SIZE>& raw) {
    double phase = raw[PHASE_INDEX] / PHASE_DIVISOR;
    if (phase < 0.0) phase = 0.0;
    if (phase > 1.0) phase = 1.0;
    double logit = polynomial(0, phase);
    for (int feature = 0; feature < FEATURE_COUNT; ++feature) {
        double normalized = raw[FEATURE_INDICES[feature]]
            / FEATURE_DIVISORS[feature];
        logit += normalized * polynomial(feature + 1, phase);
    }
    return std::tanh(0.5 * logit);
}

}  // namespace gen217_value_model
