#!/usr/bin/env python3
"""Export a fitted value model JSON as a dependency-free C++ header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def format_number(value: float) -> str:
    return format(float(value), ".17g")


def format_vector(values: list[float], indent: str = "    ") -> str:
    return indent + (",\n" + indent).join(format_number(value) for value in values)


def render_relu(document: dict, namespace: str) -> str:
    hidden_weights = document["hidden_weights"]
    hidden_size = len(hidden_weights)
    feature_names = document["feature_order"]
    input_divisors = document["input_scales_before_standardization"]
    input_size = len(feature_names)
    if hidden_size == 0 or any(len(row) != input_size for row in hidden_weights):
        raise ValueError(f"expected hidden weights with shape (H, {input_size})")
    if len(input_divisors) != input_size:
        raise ValueError("input divisor count does not match feature count")
    hidden_rows = ",\n".join(
        "    {" + ", ".join(format_number(value) for value in row) + "}"
        for row in hidden_weights
    )
    return f"""#pragma once

#include <array>
#include <cmath>

// Generated by scripts/export_value_model_header.py from
// src/ai/value_model_gen217.json. Do not edit coefficients by hand.
namespace {namespace} {{

static const int INPUT_SIZE = {input_size};
static const int HIDDEN_SIZE = {hidden_size};
static const double INPUT_DIVISORS[INPUT_SIZE] = {{
{format_vector(input_divisors)}
}};
static const double INPUT_MEAN[INPUT_SIZE] = {{
{format_vector(document['input_mean'])}
}};
static const double INPUT_SCALE[INPUT_SIZE] = {{
{format_vector(document['input_scale'])}
}};
static const double HIDDEN_WEIGHTS[HIDDEN_SIZE][INPUT_SIZE] = {{
{hidden_rows}
}};
static const double HIDDEN_BIAS[HIDDEN_SIZE] = {{
{format_vector(document['hidden_bias'])}
}};
static const double OUTPUT_WEIGHTS[HIDDEN_SIZE] = {{
{format_vector(document['output_weights'])}
}};
static const double OUTPUT_BIAS = {format_number(document['output_bias'])};

inline double evaluate(const std::array<double, INPUT_SIZE>& raw) {{
    double input[INPUT_SIZE];
    for (int i = 0; i < INPUT_SIZE; ++i) {{
        double normalized = raw[i] / INPUT_DIVISORS[i];
        input[i] = (normalized - INPUT_MEAN[i]) / INPUT_SCALE[i];
    }}

    double logit = OUTPUT_BIAS;
    for (int hidden = 0; hidden < HIDDEN_SIZE; ++hidden) {{
        double activation = HIDDEN_BIAS[hidden];
        for (int inputIndex = 0; inputIndex < INPUT_SIZE; ++inputIndex) {{
            activation += HIDDEN_WEIGHTS[hidden][inputIndex] * input[inputIndex];
        }}
        if (activation > 0.0) {{
            logit += OUTPUT_WEIGHTS[hidden] * activation;
        }}
    }}
    return std::tanh(0.5 * logit);
}}

}}  // namespace {namespace}
"""


def render_formula(document: dict, namespace: str) -> str:
    feature_names = document["feature_order"]
    input_size = len(feature_names)
    phase_index = int(document["phase_index"])
    phase_degree = int(document["phase_degree"])
    feature_indices = document["coefficient_feature_indices"]
    feature_divisors = document["coefficient_feature_divisors"]
    coefficients = document["coefficients"]
    group_count = 1 + len(feature_indices)
    if len(coefficients) != group_count or any(
        len(row) != phase_degree + 1 for row in coefficients
    ):
        raise ValueError("formula coefficient shape does not match its schema")
    if len(feature_divisors) != len(feature_indices):
        raise ValueError("formula feature divisor count does not match")
    coefficient_rows = ",\n".join(
        "    {" + ", ".join(format_number(value) for value in row) + "}"
        for row in coefficients
    )
    return f"""#pragma once

#include <array>
#include <cmath>

// Generated by scripts/export_value_model_header.py. Do not edit coefficients
// by hand.
namespace {namespace} {{

static const int INPUT_SIZE = {input_size};
static const int PHASE_INDEX = {phase_index};
static const int PHASE_DEGREE = {phase_degree};
static const int FEATURE_COUNT = {len(feature_indices)};
static const double PHASE_DIVISOR = {format_number(document['phase_divisor'])};
static const int FEATURE_INDICES[FEATURE_COUNT] = {{
{format_vector(feature_indices)}
}};
static const double FEATURE_DIVISORS[FEATURE_COUNT] = {{
{format_vector(feature_divisors)}
}};
static const double COEFFICIENTS[FEATURE_COUNT + 1][PHASE_DEGREE + 1] = {{
{coefficient_rows}
}};

inline double polynomial(int group, double phase) {{
    double value = COEFFICIENTS[group][PHASE_DEGREE];
    for (int degree = PHASE_DEGREE - 1; degree >= 0; --degree) {{
        value = value * phase + COEFFICIENTS[group][degree];
    }}
    return value;
}}

inline double evaluate(const std::array<double, INPUT_SIZE>& raw) {{
    double phase = raw[PHASE_INDEX] / PHASE_DIVISOR;
    if (phase < 0.0) phase = 0.0;
    if (phase > 1.0) phase = 1.0;
    double logit = polynomial(0, phase);
    for (int feature = 0; feature < FEATURE_COUNT; ++feature) {{
        double normalized = raw[FEATURE_INDICES[feature]]
            / FEATURE_DIVISORS[feature];
        logit += normalized * polynomial(feature + 1, phase);
    }}
    return std::tanh(0.5 * logit);
}}

}}  // namespace {namespace}
"""


def render(document: dict, namespace: str = "gen217_value_model") -> str:
    model_type = document.get("model_type")
    if model_type == "relu_mlp":
        return render_relu(document, namespace)
    if model_type == "phase_formula":
        return render_formula(document, namespace)
    raise ValueError(f"unsupported model type: {model_type}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("model_json", type=Path)
    parser.add_argument("output_header", type=Path)
    parser.add_argument("--namespace", default="gen217_value_model")
    args = parser.parse_args()
    document = json.loads(args.model_json.read_text(encoding="utf-8"))
    args.output_header.parent.mkdir(parents=True, exist_ok=True)
    args.output_header.write_text(
        render(document, namespace=args.namespace), encoding="utf-8"
    )
    print(f"Wrote {args.output_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
